### ISSUE TITLE
Merging requires signed commits

### ISSUE THREAD

**Issue by vincent-zurczak** [bats-core/bats-detik#22]
Hello all.

I have reviewed some merge requests this morning but I cannot merge them (in rebase mode) because commits are not signed. It indicates `The base branch requires all commits to be signed`.

I wanted to know: is it a global setting for all the git repositories in this organization?
@bats-core/bats-detik @bats-core/bats-core 

Thanks for your help.

**Comment by sublimino** [comment]
Hi @vincent-zurczak, it's a per-repo setting. I can see it's been [enabled and working](https://github.com/bats-core/bats-detik/commits/master), is this a problem merging PRs that are not signed? If so, they can be historically signed by rebasing them and pushed back to the branch before merge.

Or if that's a problem we can disable signing for this repo, although the goal would be to have signed commits enabled again in the future. :blush:

**Comment by vincent-zurczak** [comment]
Hi @sublimino,

We can ask people to sign their commits, no problem with that. I will add a file about contributions.
However, I noticed we cannot merge PRs with rebase anymore. It seems related to [they way Github handles rebasing](https://github.com/renovatebot/renovate/issues/1828). Only merge  and merge with squash methods work.

**Comment by jasonkarns** [comment]
I'm confused how merge-with-squash would work. GitHub itself doesn't sign commits, right? It doesn't have anyone's private key. So how would the squashed commit be signed?

**Comment by martin-schulze-vireso** [comment]
@jasonkarns IIRC actions with your account in GitHub always create commits that GitHub displays as signed. However, they are most likely not PGP signed, as you pointed out.

**Comment by vincent-zurczak** [comment]
I cannot explain it myself.
[This PR](https://github.com/bats-core/bats-detik/pull/20) had one signed commit. All the flags were green to merge it: merge with rebase did not work, but merge with squash did (there was one commit, so no big deal). If you look at [the history](https://github.com/bats-core/bats-detik/commits/master), the commit appears without any merge commit. But when there are more than one commit and you want to preserve them (like in [this PR](https://github.com/bats-core/bats-detik/pull/21)), only the merge commit is suitable.

Anyway, this is issue was in fact mostly about how to merge contributions with signed commits. My understanding is that the merge commit is the best solution (that works in all cases).

**Comment by sublimino** [comment]
_(to the best of my understanding!)_

Github has its own "Webflow" signing key to get around the "all commits should be signed" issue. Using rebase/squash that's what used. That destroys trust history of the actual commit signers (e.g. gpg signed metadata is linked to each commit's SHA) so squashing/rebasing is disabled everywhere I can configure branch controls : ]

(This key is also used for some Github in-browser edit where signing is required, IIUC)

![image](https://user-images.githubusercontent.com/134117/116121273-5da1a500-a6b8-11eb-9dff-2f1a39e2129c.png)

> merge with rebase did not work, but merge with squash did (there was one commit, so no big deal)

As it's a single commit, it didn't truly get "squashed" by Github and it was able to cleanly apply to master as the parent commit was the same on both branches. Merge commits "bridge" this process when there's no common parent, and introduce no new code. They're signed by the same webflow key, unless done on a user's machine with their own GPG key.

>  But when there are more than one commit and you want to preserve them (like in this PR), only the merge commit is suitable.

Strong agree, merging keeps all the previous signatures as the commits change branches, and so is preferred : ]
