### ISSUE TITLE
Passing a complex jsonpath as a property

### ISSUE THREAD

**Issue by rajula96reddy** [bats-core/bats-detik#23]
Hey,

When passing a jsonpath like `.status.conditions[?(@.type=="Test")].name` with the following line
```
run try "at most 5 times every 2s to get custom-resource named site' and verify that '.status.conditions[?(@.type==\"Test\")].name' is 'ABC'"
```
doesn't work because, detik generates the client query as
`oc --namespace=test get custom-resource -o custom-columns=NAME:.metadata.name,PROP:.status.conditions[?(@.type==\"Test\")].name` 
which causes `error: unrecognized identifier Initialized` from the client.

This can simply fixed by passing the complex jsonpath in single quotes, which will make the client query 
`oc --namespace=test get custom-resource -o custom-columns=NAME:.metadata.name,PROP:'.status.conditions[?(@.type==\"Test\")].name'`

If we can agree on this I can create a PR (only requires changing [L266](https://github.com/bats-core/bats-detik/blob/master/lib/detik.bash#L266)) to fix this. Thanks! :smile:

**Comment by vincent-zurczak** [comment]
Hi!

Sure, a PR will be welcome to fix it. :wink: 
Please, add a test also in [this file](https://github.com/bats-core/bats-detik/blob/master/tests/test.detik.try.to.verify.bats) so that we can detect any regression with this kind of path.
