### ISSUE TITLE
Switch the CI to Github actions and restore the Docker build

### ISSUE THREAD

**Issue by vincent-zurczak** [bats-core/bats-detik#26]
BATS Core is already using it.
And it prevents limits from Docker Hub.

**Comment by vincent-zurczak** [comment]
Hi @bats-core/bats-detik @bats-core/bats-core!  
Do we have an organization account for Docker hub? It could be used not only to pull base images, but also to publish official ones. Are the secrets [used here](https://github.com/bats-core/bats-core/blob/master/.github/workflows/release.yml) available for all the repositories in this organization?

**Comment by martin-schulze-vireso** [comment]
There is an [account](https://hub.docker.com/r/bats/bats) but it is just a normal user account, not an organization. This account is already used to publish official images for bats-core. The secrets are at the bats-core organization level, so they might be available here too.

**Comment by vincent-zurczak** [comment]
OK, thanks! :+1: 
I will make some tests.
