### ISSUE TITLE
Support regex validation of property values

### ISSUE THREAD

**Issue by cognifloyd** [bats-core/bats-detik#34]
Whenever detik is asked to verify a property value, it checks for equality with the expected value:
https://github.com/bats-core/bats-detik/blob/48b29b48026adda352adf07f8b9b8df13e9c84df/lib/detik.bash#L230

I would like to use a regex to verify that
- a given string is in `.spec.containers[*].command[*]` or
- that an annotation starts with or ends with a particular value.

The annotation is calculated in a helm chart, so I need to test and make sure that calculation is correct.

So, something like:
```
sensor_podname="stackstorm-ha-st2sensorcontainer-"  # the prefix for the pod name

verify "'.spec.containers[*].command[*]' is '.*,--sensor-ref=.*' for pods named '${sensor_podname}'"

try "at most 1 times every 5s to find 1 pod named '${sensor_podname}'" \
    "and verify that '.metadata.annotations.stackstorm/sensor-hash-ranges' is '0\.\.[0-9]+'"
try "at most 1 times every 5s to find 1 pod named '${sensor_podname}'" \
    "and verify that '.metadata.annotations.stackstorm/sensor-hash-ranges' is '[1-9][0-9]*\.\.4294967"
```

**Comment by vincent-zurczak** [comment]
Hi @cognifloyd.

It should be feasible, but a dedicated syntax will be necessary.
Rather than `is`, I can introduce the `matches` keyword to distinguish the cases. It will also require decisions about the regex syntax: BASH regexp are not exactly the same we use in programming languages. I have to think about what would be the most convenient.

Another solution is to introduce another keyword to search in array values.
I will have a look at this from next week, when I am back from holidays.

**Comment by cognifloyd** [comment]
A different keyword makes sense.

I need to do a partial match on any element in the array. I'm fine with bash or grep or whatever regex. Globbing would be fine too. Just document which format to use for searching.

**Comment by vincent-zurczak** [comment]
Hi @cognifloyd!
I have worked on this feature. Things seem OK from my side. Could you give it a try and tell me if it meets your expectations? Everything is on a [separate branch](https://github.com/bats-core/bats-detik/tree/%2334#using-regular-expressions).

**Comment by cognifloyd** [comment]
Sorry, I've been working on another project lately. I'll get back to the helm chart stuff around mid February I hope.

Thank you so much for working on this! I'll test it when I can.

**Comment by cognifloyd** [comment]
I'm sorry I'm not going to get to this any time soon. I ended up using `helm-unittest` for what I needed. I still think this would be useful but I don't think I'm going to have time to do significant helm chart development where I might use this for a long time.

**Comment by vincent-zurczak** [comment]
Hi @cognifloyd.
No problem. At least, you pushed a new feature idea. I will verify the branch and merge it into the main one.

**Comment by brokenpip3** [comment]
hey @vincent-zurczak do you have in mind to release a new version after this nice new feature? 
Thanks!

**Comment by vincent-zurczak** [comment]
Hello @brokenpip3,

Thank you for this reminder.
I have just created a new release and tag that includes this feature.

**Comment by brokenpip3** [comment]
Great thanks!
Will update the brew package and the github action today :)
