### ISSUE TITLE
Cannot verify for objects with dots

### ISSUE THREAD

**Issue by e-minguez** [bats-core/bats-detik#43]
We are trying to use Detik for some tests and for objects where a short name collides with others, we need to use the full object name and Detik doesn't seem to like it.

```
verify "'.value' is 'false' for settings.management.cattle.io named 'first-login'"
```

**Comment by vincent-zurczak** [comment]
Hi @e-minguez.
Indeed, resource names have been all considered to follow this regular expression: `[a-z]+`.
CRDs had not been planned at the time. We can and should extend the pattern to include a dot.

**Comment by vincent-zurczak** [comment]
A PR has been submitted for review.
Hopefully, it should be soon available.

**Comment by vincent-zurczak** [comment]
I have created the tag v1.3.1 that solves this issue.
