### ISSUE TITLE
Resource Type Pattern doesn't match Ec2NodeClass custom resources

### ISSUE THREAD

**Issue by kassof** [bats-core/bats-detik#48]
I use the bats-detik library to run functional tests on my EKS cluster. I would like to test the existence and status of a custom resource **ec2nodeclass**. But all tests on a ec2nodeclass resource type fail with "Invalid expression: it does not respect the expected syntax."  

It's because the **resource type pattern**, in the utils.bash, does not accept numeric characters. 

``` 
# The pattern for resource types
# (pod, PODs, complex.crd.resource, etc.)
 resource_type_pattern="[a-z][a-z.]+"
```

Is it possible to modify this regex to accept those numeric characters ?

**Comment by vincent-zurczak** [comment]
Hello @kassof.
Sure, we can update the pattern to support this resource name. I will tell you once it is done.

**Comment by vincent-zurczak** [comment]
I have just pushed a PR: https://github.com/bats-core/bats-detik/pull/49
Once it gets an approval, we will tag a new version.

**Comment by vincent-zurczak** [comment]
The tag v1.3.3 has been released and fixes it.

**Comment by kassof** [comment]
Thanks a lot @vincent-zurczak
